# Generated by Django 3.2.3 on 2021-07-19 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210716_2018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_post', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_stories', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
