# Generated by Django 3.2.3 on 2021-08-02 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20210723_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tagFriends',
            field=models.ManyToManyField(blank=True, null=True, through='posts.TagFriends', to=settings.AUTH_USER_MODEL),
        ),
    ]
