# Generated by Django 3.2.3 on 2021-08-07 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210716_2018'),
        ('posts', '0006_alter_post_tagfriends'),
    ]

    operations = [
        migrations.CreateModel(
            name='likesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_likesPost', to='users.profile')),
            ],
            options={
                'verbose_name': 'Model base',
                'abstract': False,
            },
        ),
    ]
