# Generated by Django 3.2.3 on 2021-08-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210716_2018'),
        ('posts', '0007_likespost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_commentsPost', to='users.profile'),
        ),
    ]
