# Generated by Django 3.2.3 on 2021-08-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_likespost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likespost',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likesPost_post', to='posts.post'),
        ),
    ]
