# Generated by Django 3.2.3 on 2021-09-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comments_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likespost',
            options={},
        ),
    ]
