# Generated by Django 3.2.3 on 2021-07-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_rol'),
        ('users', '0003_auto_20210708_1719'),
    ]

    operations = [
    ]
