# Generated by Django 3.2.3 on 2021-08-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210716_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='followed',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
