# Generated by Django 3.2.3 on 2021-07-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
